data_root: /opt/yolov11/dataset/datasetYolo
work_dir: /opt/training_extensions/library/otx-workspace
task: DETECTION
callback_monitor: val/map_50
disable_infer_num_classes: false
engine:
  device: auto
  num_devices: 1
data:
  task: DETECTION
  data_format: yolo
  train_subset:
    batch_size: 48
    subset_name: train
    transforms:
    - class_path: otx.data.transform_libs.torchvision.CachedMosaic
      init_args:
        random_pop: false
        max_cached_images: 20
        img_scale: $(input_size) * 1.538
    - class_path: otx.data.transform_libs.torchvision.RandomAffine
      init_args:
        border: $(input_size) * 1.538 * -0.5
    - class_path: otx.data.transform_libs.torchvision.PhotoMetricDistortion
    - class_path: otx.data.transform_libs.torchvision.Resize
      init_args:
        scale: $(input_size) * 1.538
        keep_ratio: true
        transform_bbox: true
    - class_path: otx.data.transform_libs.torchvision.RandomFlip
      init_args:
        prob: 0.5
    - class_path: otx.data.transform_libs.torchvision.Pad
      init_args:
        pad_to_square: true
        pad_val: 114
        is_numpy_to_tvtensor: true
    - class_path: torchvision.transforms.v2.RandomVerticalFlip
      enable: false
    - class_path: otx.data.transform_libs.torchvision.RandomGaussianBlur
      enable: false
      init_args:
        kernel_size: 5
    - class_path: torchvision.transforms.v2.ToDtype
      init_args:
        dtype: ${as_torch_dtype:torch.float32}
    - class_path: otx.data.transform_libs.torchvision.RandomGaussianNoise
      enable: false
    - class_path: torchvision.transforms.v2.Normalize
      init_args:
        mean:
        - 123.675
        - 116.28
        - 103.53
        std:
        - 58.395
        - 57.12
        - 57.375
    transform_lib_type: TORCHVISION
    num_workers: 2
    sampler:
      class_path: otx.data.samplers.balanced_sampler.BalancedSampler
      init_args: {}
    to_tv_image: false
  val_subset:
    batch_size: 8
    subset_name: val
    transforms:
    - class_path: otx.data.transform_libs.torchvision.Resize
      init_args:
        scale: $(input_size)
        keep_ratio: true
    - class_path: otx.data.transform_libs.torchvision.Pad
      init_args:
        pad_to_square: true
        pad_val: 114
        is_numpy_to_tvtensor: true
    - class_path: torchvision.transforms.v2.ToDtype
      init_args:
        dtype: ${as_torch_dtype:torch.float32}
    - class_path: torchvision.transforms.v2.Normalize
      init_args:
        mean:
        - 123.675
        - 116.28
        - 103.53
        std:
        - 58.395
        - 57.12
        - 57.375
    transform_lib_type: TORCHVISION
    num_workers: 2
    sampler:
      class_path: torch.utils.data.RandomSampler
      init_args: {}
    to_tv_image: false
  test_subset:
    batch_size: 8
    subset_name: test
    transforms:
    - class_path: otx.data.transform_libs.torchvision.Resize
      init_args:
        scale: $(input_size)
        keep_ratio: true
    - class_path: otx.data.transform_libs.torchvision.Pad
      init_args:
        pad_to_square: true
        pad_val: 114
        is_numpy_to_tvtensor: true
    - class_path: torchvision.transforms.v2.ToDtype
      init_args:
        dtype: ${as_torch_dtype:torch.float32}
    - class_path: torchvision.transforms.v2.Normalize
      init_args:
        mean:
        - 123.675
        - 116.28
        - 103.53
        std:
        - 58.395
        - 57.12
        - 57.375
    transform_lib_type: TORCHVISION
    num_workers: 2
    sampler:
      class_path: torch.utils.data.RandomSampler
      init_args: {}
    to_tv_image: false
  tile_config:
    enable_tiler: false
    enable_adaptive_tiling: true
    tile_size:
    - 400
    - 400
    overlap: 0.2
    iou_threshold: 0.45
    max_num_instances: 1500
    object_tile_ratio: 0.03
    sampling_ratio: 1.0
    with_full_img: false
  image_color_channel: RGB
  include_polygons: false
  ignore_index: 255
  unannotated_items_ratio: 0.0
  auto_num_workers: false
  input_size:
  - 416
  - 416
  input_size_multiplier: 1
checkpoint: best_checkpoint.ckpt
export_format: OPENVINO
export_precision: FP16
explain: false
export_demo_package: false
max_epochs: 50
min_epochs: 1
deterministic: false
precision: 16
callbacks:
- class_path: otx.backend.native.callbacks.adaptive_early_stopping.EarlyStoppingWithWarmup
  init_args:
    monitor: val/map_50
    min_delta: 0.001
    patience: 10
    verbose: false
    mode: max
    strict: true
    check_finite: true
    check_on_train_epoch_end: false
    log_rank_zero_only: false
    warmup_iters: 30
    warmup_epochs: 3
- class_path: lightning.pytorch.callbacks.ModelCheckpoint
  init_args:
    dirpath: ''
    filename: checkpoints/epoch_{epoch:03d}
    monitor: val/map_50
    verbose: false
    save_last: true
    save_top_k: 1
    save_weights_only: false
    mode: max
    auto_insert_metric_name: false
    enable_version_counter: true
resume: false
adaptive_bs: None
check_val_every_n_epoch: 1
num_sanity_val_steps: 0
gradient_clip_val: 35.0
strategy: auto
num_nodes: 1
fast_dev_run: false
max_steps: -1
overfit_batches: 0.0
accumulate_grad_batches: 1
inference_mode: true
use_distributed_sampler: true
detect_anomaly: false
barebones: false
sync_batchnorm: false
reload_dataloaders_every_n_epochs: 0
model:
  class_path: otx.backend.native.models.detection.YOLOX
  init_args:
    data_input_params:
      input_size:
      - 416
      - 416
      mean:
      - 123.675
      - 116.28
      - 103.53
      std:
      - 58.395
      - 57.12
      - 57.375
    model_name: yolox_tiny
    metric: otx.metrics.fmeasure._mean_ap_f_measure_callable
    torch_compile: false
